name: deep_scanner
description: Document scanner using deep autoencoders for denoising

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: 0.6.0+11
  path_provider: ^1.4.5
  path: 1.6.4
  cupertino_icons: ^0.1.2
  dio: 3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  image_path: "dev_assets/icons/icon.png"
  adaptive_icon_background: "dev_assets/icons/background.png"
  adaptive_icon_foreground: "dev_assets/icons/foreground.png"

flutter:
  assets:
    - assets/images/
  uses-material-design: true

# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
